### ISSUE TITLE
asset won't resolve without `0x` prefix

### ISSUE THREAD

**Issue by diminator** [oceanprotocol/squid-py#136]
Step 1: create assets with `squid-js` and `squid-py`
```
$ ./tuna.py assets/search -c node -i weather
[
  "did:op:0xb5dba4c2994040178f9c908cd5ef46b29b25468300f247b7a8f09d4edf57beea",
  "did:op:0bd1318b7a324557ae311d40dad8cc890f4547dd125e413d8bbd42fc74ca8caf",
]
```
(Step 1b): notice the length difference due to the `0x` prefix generated in python

Step 2: resolve the assets generated with `squid-js` (ie the ones without `0x`)

```
$ ./tuna.py assets/resolve -c python -i did:op:0bd1318b7a324557ae311d40dad8cc890f4547dd1
25e413d8bbd42fc74ca8caf
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/dimi/oceanprotocol/tuna/python/assets/resolve.py", line 12, in <module>
    ddo = ocean.resolve_did(INPUT)
  File "/home/dimi/oceanprotocol/tuna/venv/lib/python3.6/site-packages/squid_py-0.2.12-py3.6.egg/squid_py/ocean/ocean.py", line 365, in reso
lve_did
    resolver = self.did_resolver.resolve(did)
  File "/home/dimi/oceanprotocol/tuna/venv/lib/python3.6/site-packages/squid_py-0.2.12-py3.6.egg/squid_py/didresolver.py", line 192, in reso
lve
    data = self.get_did(did_bytes)
  File "/home/dimi/oceanprotocol/tuna/venv/lib/python3.6/site-packages/squid_py-0.2.12-py3.6.egg/squid_py/didresolver.py", line 244, in get_
did
    raise OceanDIDNotFound('cannot find DID {}'.format(Web3.toHex(did_bytes)))
squid_py.exceptions.OceanDIDNotFound: cannot find DID 0x0bd1318b7a324557ae311d40dad8cc890f4547dd125e413d8bbd42fc74ca8caf
```

**Comment by ssallam** [comment]
Actually, I  think this is unrelated to the 0x prefix. The problem is that the asset was registered in different keeper contracts. It is in the same keeper network, but a different didregistery contract deployment.

**Comment by ssallam** [comment]
Fixed.
