### ISSUE TITLE
query search is broken

### ISSUE THREAD

**Issue by diminator** [oceanprotocol/squid-py#139]
```
(venv) dimi@dimi-xps: tuna (feature/sign-agreement) $ ./tuna.py assets/search -c python -i weather
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/dimi/oceanprotocol/tuna/python/assets/search.py", line 12, in <module>
    assets = ocean.search_assets(INPUT)
  File "/home/dimi/oceanprotocol/tuna/venv/lib/python3.6/site-packages/squid_py-0.2.13-py3.6.egg/squid_py/ocean/ocean
.py", line 140, in search_assets
    return [Asset.from_ddo_dict(i) for i in aquarius.query_search(query)]
  File "/home/dimi/oceanprotocol/tuna/venv/lib/python3.6/site-packages/squid_py-0.2.13-py3.6.egg/squid_py/aquariuswra
pper.py", line 106, in query_search
    parsed_response = json.loads(response)
  File "/usr/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```
```
(venv) dimi@dimi-xps: tuna (feature/sign-agreement) $ ./tuna.py assets/search -c node -i weather
[
  "did:op:3597a39818d598e5d60b83eabe29e337d37d9ed5af218b4af5e94df9f7d9783a",
  "did:op:0x36674954d8414f4c87a53babb67cd443596edb870268498ca923dd44a42c4368",
  "did:op:0xe7f8651e3a3f473499ae24f6f19f8573870735fdad76415b93143999cc1338dd",
  "did:op:0x206057f53970417595df180e2491e790c6343d1d68b947a9a742bee08c21c375",
  "did:op:0x0edcb53988164618ba575e41804b08072ae2e6069793412e92a7eaab7aa870a7",
  "did:op:0xdba8d99e74844df584fd51f3b014f52a2ac12841dcde46cfb0e6a6f99cb26231"
]
```

**Comment by innoprenuer** [comment]
There are 2 search functions, earlier search_assets() implemented text search and search_assets_by_text() was just empty TODO function, which was incorrect and inconsistent with squid-js implementation. Now, it is fixed. So, use

for text search -
```
    def search_assets_by_text(self, text, sort=None, offset=100, page=0, aquarius_url=None):
        """
        Search an asset in oceanDB using aquarius.
        :param text String with the value that you are searching.
        :param sort Dictionary to choose order base in some value.
        :param offset Number of elements shows by page.
        :param page Page number.
        :param aquarius_url Url of the aquarius where you want to search. If there is not provided take the default.
        :return: List of assets that match with the query.
        """
```
and for Query search - 

```
    def search_assets(self, query):
        """
        Search an asset in oceanDB using search query.
        :param query dict with query parameters
            (e.g.) {"offset": 100, "page": 0, "sort": {"value": 1},
                    query: {"service:{$elemMatch:{"metadata": {$exists : true}}}}}
                    Here, OceanDB instance of mongodb can leverage power of mongo queries in 'query' attribute.
                    For more info - https://docs.mongodb.com/manual/reference/method/db.collection.find
        :return: List of assets that match with the query.
        """
```

**Comment by diminator** [comment]
Also fails on empty DB

```
(venv) dimi@dimi-xps: tuna (feature/sign-agreement) $ ./tuna.py assets/search -c node -i weather
[]
```

```
(venv) dimi@dimi-xps: tuna (feature/sign-agreement) $ ./tuna.py assets/search -c python -i weather
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/dimi/oceanprotocol/tuna/python/assets/search.py", line 12, in <module>
    assets = ocean.search_assets(INPUT)
  File "/home/dimi/oceanprotocol/tuna/venv/lib/python3.6/site-packages/squid_py-0.2.13-py3.6.egg/squid_py/ocean/ocean
.py", line 140, in search_assets
    return [Asset.from_ddo_dict(i) for i in aquarius.query_search(query)]
  File "/home/dimi/oceanprotocol/tuna/venv/lib/python3.6/site-packages/squid_py-0.2.13-py3.6.egg/squid_py/aquariuswra
pper.py", line 106, in query_search
    parsed_response = json.loads(response)
  File "/usr/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by diminator** [comment]
I guess this is wrong error messaging / poor logging?

**Comment by diminator** [comment]
> Now, it is fixed. So, use

this works indeed

**Comment by innoprenuer** [comment]
can we close this?

**Comment by MarcusJones** [comment]
@innoprenuer We need to correct the docstring on `def search_assets(self, query)`

**Comment by eruizgar91** [comment]
#162
