### ISSUE TITLE
remove logging asserts

### ISSUE THREAD

**Issue by diminator** [oceanprotocol/squid-py#155]
## Expected Behavior

No errors or business logic introduced by logging
Advise: Do not introduce complex logging logic. ONLY log available values

## Current Behavior

```
./tuna.py sea/execute -c python -i ....
```

## Failure Information (for bugs)
gives
```
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/dimi/oceanprotocol/tuna/python/sea/execute.py", line 29, in <module>
    publisher_address=ocean.main_account.address)
  File "/home/dimi/oceanprotocol/tuna/venv/lib/python3.6/site-packages/squid_py/ocean/ocean.py", line 337, in execute_service_agreement
    consumer_address, service_agreement_signature, ddo=ddo
  File "/home/dimi/oceanprotocol/tuna/venv/lib/python3.6/site-packages/squid_py/ocean/ocean.py", line 416, in verify_service_agreement_signature
    self._log_conditions_keys(sa)
  File "/home/dimi/oceanprotocol/tuna/venv/lib/python3.6/site-packages/squid_py/ocean/ocean.py", line 556, in _log_conditions_keys
    assert values[3] == sa.conditions_keys
AssertionError
Using default logging settings.
```

**Comment by ssallam** [comment]
This has been refactored. Logging and validation are separate.
