### ISSUE TITLE
Traceback when getting a "0x00..." address from a contract call.

### ISSUE THREAD

**Issue by ssallam** [oceanprotocol/squid-py#250]
Traceback when using squid in Brizo on executing agreement:
```
2019-01-16 15:46:00 sallam-XPS-13-9370 brizo[25824] ERROR int() can't convert non-string with explicit base
Traceback (most recent call last):
  File "/home/ssallam/pycharm_projects/brizo/brizo/routes.py", line 112, in initialize
    config.parity_password)
  File "/home/ssallam/pycharm_projects/brizo/venv/lib/python3.6/site-packages/squid_py/ocean/ocean.py", line 368, in execute_service_agreement
    service_agreement_id) is not None:
  File "/home/ssallam/pycharm_projects/brizo/venv/lib/python3.6/site-packages/squid_py/keeper/service_agreement.py", line 127, in get_service_agreement_consumer
    return self.contract_concise.getServiceAgreementConsumer(service_agreement_id)
  File "/home/ssallam/pycharm_projects/brizo/venv/lib/python3.6/site-packages/web3/contract.py", line 879, in __call__
    return self.__prepared_function(*args, **kwargs)
  File "/home/ssallam/pycharm_projects/brizo/venv/lib/python3.6/site-packages/web3/contract.py", line 892, in __prepared_function
    return getattr(self._function(*args), modifier)(modifier_dict)
  File "/home/ssallam/pycharm_projects/brizo/venv/lib/python3.6/site-packages/web3/contract.py", line 1106, in call
    **self.kwargs
  File "/home/ssallam/pycharm_projects/brizo/venv/lib/python3.6/site-packages/web3/contract.py", line 1391, in call_contract_function
    normalized_data = map_abi_data(_normalizers, output_types, output_data)
  File "cytoolz/functoolz.pyx", line 236, in cytoolz.functoolz.curry.__call__
  File "cytoolz/functoolz.pyx", line 232, in cytoolz.functoolz.curry.__call__
  File "/home/ssallam/pycharm_projects/brizo/venv/lib/python3.6/site-packages/web3/utils/abi.py", line 442, in map_abi_data
    return pipe(data, *pipeline)
  File "cytoolz/functoolz.pyx", line 589, in cytoolz.functoolz.pipe
  File "cytoolz/functoolz.pyx", line 565, in cytoolz.functoolz.c_pipe
  File "cytoolz/functoolz.pyx", line 236, in cytoolz.functoolz.curry.__call__
  File "cytoolz/functoolz.pyx", line 232, in cytoolz.functoolz.curry.__call__
  File "/home/ssallam/pycharm_projects/brizo/venv/lib/python3.6/site-packages/web3/utils/abi.py", line 474, in data_tree_map
    return recursive_map(map_to_typed_data, data_tree)
  File "/home/ssallam/pycharm_projects/brizo/venv/lib/python3.6/site-packages/web3/utils/decorators.py", line 35, in wrapped
    wrapped_val = to_wrap(*args)
  File "/home/ssallam/pycharm_projects/brizo/venv/lib/python3.6/site-packages/web3/utils/formatters.py", line 115, in recursive_map
    items_mapped = map_collection(recurse, data)
  File "/home/ssallam/pycharm_projects/brizo/venv/lib/python3.6/site-packages/web3/utils/formatters.py", line 102, in map_collection
    return datatype(map(func, collection))
  File "/home/ssallam/pycharm_projects/brizo/venv/lib/python3.6/site-packages/web3/utils/formatters.py", line 114, in recurse
    return recursive_map(func, item)
  File "/home/ssallam/pycharm_projects/brizo/venv/lib/python3.6/site-packages/web3/utils/decorators.py", line 35, in wrapped
    wrapped_val = to_wrap(*args)
  File "/home/ssallam/pycharm_projects/brizo/venv/lib/python3.6/site-packages/web3/utils/formatters.py", line 116, in recursive_map
    return func(items_mapped)
  File "/home/ssallam/pycharm_projects/brizo/venv/lib/python3.6/site-packages/web3/utils/abi.py", line 471, in map_to_typed_data
    return ABITypedData(func(*elements))
  File "/home/ssallam/pycharm_projects/brizo/venv/lib/python3.6/site-packages/web3/contract.py", line 940, in _none_addr
    if datatype == 'address' and int(data, base=16) == 0:
TypeError: int() can't convert non-string with explicit base
```

This occurs when checking whether service agreement already exists by checking for service consumer.

**Comment by ssallam** [comment]
Fixed.
