### ISSUE TITLE
Ordered asset DID not found on-chain in the current did registry

### ISSUE THREAD

**Issue by weetok** [oceanprotocol/squid-py#341]
## Expected Behavior

Asset to be ordered found on the ocean block chain 

## Current Behavior

Retrieved assets (by assets.search() ) is not found on-chain of current did registry.

## Failure Information (for bugs)

squid_py.exceptions.OceanDIDNotFound: DID "0x5b8d18fc6fe44e7ba760e5c4a779662f33bdda945ebb43719d5818e54e7e88ca" is not found on-chain in the current did registry. Please ensure assets are registered in the correct keeper contracts. The keeper-contracts DIDRegistry address is 0xC6Db052cb5b24054B60EE4d1aFaBdB345452B39e

## Step to Reproduce the problem

Please provide detailed steps for reproducing the issue.

1. Install and configure the usage example given in this repo (including the barge part) locally
2. Run usage.py

## Specifications

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Version: latest (with aquarius v0.2.2)
* Python: 3.7
* OS: linux, ArchLinux

## Failure Logs

/home/a690251/projects/odyssey/Heimdallr/venv/bin/python /home/a690251/projects/odyssey/Heimdallr/usage.py
2019-04-13 14:43:13 RosesAreRed root[23220] INFO Logging configuration loaded from file: logging.yaml
2019-04-13 14:43:13,258 - keeper - DEBUG - Loaded Dispenser at 0xcc2353edb989BCcFeb682aeEB7D56497F61fdbfA
2019-04-13 14:43:13,283 - keeper - DEBUG - Loaded OceanToken at 0xE6F83ee0815e8A9A23146677B66D959f776ea07e
2019-04-13 14:43:13,303 - keeper - DEBUG - Loaded DIDRegistry at 0xC6Db052cb5b24054B60EE4d1aFaBdB345452B39e
2019-04-13 14:43:13,322 - keeper - DEBUG - Loaded TemplateStoreManager at 0x94e47a2516249De6c44d0aab42f94b74f93e4854
2019-04-13 14:43:13,344 - keeper - DEBUG - Loaded EscrowAccessSecretStoreTemplate at 0x49917665Dd169FBbb7752A7903F99Dde96E01B7A
2019-04-13 14:43:13,364 - keeper - DEBUG - Loaded AgreementStoreManager at 0xA5481Ff71862A4240152948f63aC927fc116133f
2019-04-13 14:43:13,385 - keeper - DEBUG - Loaded ConditionStoreManager at 0x014A75Ffe45e7A54aE8811Bf4B50A6C0Ef7C43D8
2019-04-13 14:43:13,404 - keeper - DEBUG - Loaded SignCondition at 0xB4eEEbA76D96F11F3C644Bb80B556f4eA622f1D0
2019-04-13 14:43:13,425 - keeper - DEBUG - Loaded LockRewardCondition at 0xBF7D4cfE97b52E79CcBADa7443472789d8E50ac4
2019-04-13 14:43:13,447 - keeper - DEBUG - Loaded EscrowReward at 0x8F730c1fC2618fefAac911486f4965d002491C4b
2019-04-13 14:43:13,467 - keeper - DEBUG - Loaded AccessSecretStoreCondition at 0x8147bf0C5e331D19c541ee3EbA40a72837352A2e
2019-04-13 14:43:13 RosesAreRed squid_py.ocean.ocean_secret_store[23220] INFO 	SecretStore: url http://localhost:12001, parity-client http://localhost:8545, account 0x00Bd138aBD70e2F00903268F3Db08f2D25677C9e
2019-04-13 14:43:13 RosesAreRed squid_py.keeper.diagnostics[23220] INFO Keeper contract artifacts (JSON abi files) at: /home/a690251/projects/odyssey/Heimdallr/artifacts
2019-04-13 14:43:13 RosesAreRed squid_py.keeper.diagnostics[23220] INFO Using keeper contracts from network spree, network id is 8996
2019-04-13 14:43:13 RosesAreRed squid_py.keeper.diagnostics[23220] INFO Looking for keeper contracts ending with ".spree.json", e.g. "AgreementStoreManager.spree.json".
2019-04-13 14:43:13,489 - keeper - DEBUG - Loaded HashLockCondition at 0x736DCC96D89cB2F9E2316cD826668f4E1c4861B0
2019-04-13 14:43:13,499 - keeper - DEBUG - Loaded Dispenser at 0xcc2353edb989BCcFeb682aeEB7D56497F61fdbfA
2019-04-13 14:43:13,499 - keeper - DEBUG - Loaded OceanToken at 0xE6F83ee0815e8A9A23146677B66D959f776ea07e
2019-04-13 14:43:13,499 - keeper - DEBUG - Loaded DIDRegistry at 0xC6Db052cb5b24054B60EE4d1aFaBdB345452B39e
2019-04-13 14:43:13,499 - keeper - DEBUG - Loaded TemplateStoreManager at 0x94e47a2516249De6c44d0aab42f94b74f93e4854
2019-04-13 14:43:13,499 - keeper - DEBUG - Loaded EscrowAccessSecretStoreTemplate at 0x49917665Dd169FBbb7752A7903F99Dde96E01B7A
2019-04-13 14:43:13,499 - keeper - DEBUG - Loaded AgreementStoreManager at 0xA5481Ff71862A4240152948f63aC927fc116133f
2019-04-13 14:43:13,499 - keeper - DEBUG - Loaded ConditionStoreManager at 0x014A75Ffe45e7A54aE8811Bf4B50A6C0Ef7C43D8
2019-04-13 14:43:13,499 - keeper - DEBUG - Loaded SignCondition at 0xB4eEEbA76D96F11F3C644Bb80B556f4eA622f1D0
2019-04-13 14:43:13,499 - keeper - DEBUG - Loaded LockRewardCondition at 0xBF7D4cfE97b52E79CcBADa7443472789d8E50ac4
2019-04-13 14:43:13,499 - keeper - DEBUG - Loaded EscrowReward at 0x8F730c1fC2618fefAac911486f4965d002491C4b
2019-04-13 14:43:13,499 - keeper - DEBUG - Loaded AccessSecretStoreCondition at 0x8147bf0C5e331D19c541ee3EbA40a72837352A2e
2019-04-13 14:43:13,499 - keeper - DEBUG - Loaded HashLockCondition at 0x736DCC96D89cB2F9E2316cD826668f4E1c4861B0
2019-04-13 14:43:13,500 - ocean - INFO - Squid Ocean instance initialized: 
2019-04-13 14:43:13,500 - ocean - INFO - 	Other accounts: ['0x00Bd138aBD70e2F00903268F3Db08f2D25677C9e', '0x068Ed00cF0441e4829D9784fCBe7b9e26D4BD8d0', '0xA99D43d86A0758d5632313b8fA3972B6088A21BB']
2019-04-13 14:43:13,500 - ocean - INFO - 	DIDRegistry @ 0xC6Db052cb5b24054B60EE4d1aFaBdB345452B39e
2019-04-13 14:43:13,500 - ocean - DEBUG - Generating new did: did:op:1c61e39a0f694b74b66e82f68fcd3b3bdc3aeb063fba49f7ad120e2616017b69
2019-04-13 14:43:13 RosesAreRed root[23220] INFO Finished loading keeper contracts:
	Dispenser: 0xcc2353edb989BCcFeb682aeEB7D56497F61fdbfA
	OceanToken: 0xE6F83ee0815e8A9A23146677B66D959f776ea07e
	DIDRegistry: 0xC6Db052cb5b24054B60EE4d1aFaBdB345452B39e
	AgreementStoreManager: 0xA5481Ff71862A4240152948f63aC927fc116133f
	TemplateStoreManager: 0x94e47a2516249De6c44d0aab42f94b74f93e4854
	ConditionStoreManager: 0x014A75Ffe45e7A54aE8811Bf4B50A6C0Ef7C43D8
	AccessSecretStoreCondition: 0x8147bf0C5e331D19c541ee3EbA40a72837352A2e
	SignCondition: 0xB4eEEbA76D96F11F3C644Bb80B556f4eA622f1D0
	LockRewardCondition: 0xBF7D4cfE97b52E79CcBADa7443472789d8E50ac4
	EscrowAccessSecretStoreTemplate: 0x49917665Dd169FBbb7752A7903F99Dde96E01B7A
	EscrowReward: 0x8F730c1fC2618fefAac911486f4965d002491C4b
	HashLockCondition: 0x736DCC96D89cB2F9E2316cD826668f4E1c4861B0
2019-04-13 14:43:13,515 - ddo - DEBUG - Adding public key 0x00Bd138aBD70e2F00903268F3Db08f2D25677C9e to the did did:op:1c61e39a0f694b74b66e82f68fcd3b3bdc3aeb063fba49f7ad120e2616017b69
2019-04-13 14:43:13,515 - ddo - DEBUG - Adding authentication {'type': 'RsaSignatureAuthentication2018', 'publicKey': 'did:op:1c61e39a0f694b74b66e82f68fcd3b3bdc3aeb063fba49f7ad120e2616017b69'}
2019-04-13 14:43:13,617 - ddo - DEBUG - Adding signature to the ddo object.
2019-04-13 14:43:13,617 - ocean - DEBUG - Encrypting content urls in the metadata.
2019-04-13 14:43:13,700 - ocean - INFO - Content urls encrypted successfully 0xd4148b4f6f3a1b1611b52edab72a734fb5890be3905b3c8f377b7b423648be463a77b5a228565e85f8b4dbc448ef5be681e353e8fbb8cad8dcf525b2990ef41d65b299d0a5dfd412ebeee2996e639faaed56ba5a1486f3429029c1afffd469b1b531e6da872ffaaba7605aedd9c331551cbbf14d58dbc7336fcf5a7c6fcd199a7ab4bfabd710c9e6a6cfff200f7d59b00125e5c8337e3b3ed3cf93530f0ed2b878892544f1a05b28a2c4e6573648a797d8161c645d0fe124c619ccb68fd8a19a3b32db43b9aace579cafebfd46d31b9b6911dd858cfc48b31afa190455a936c0cae3a1a0cd69e681fe63547cd8a5c928150ce380b595edb0968178c8aa40a0a7727edf0c3d21d255e8cb8acb610cbabc47fb3edaa87f1edbac47feed9d3b6f31a5488ab6f7e29a2a04bd71502d568f6190e70c1df1b54d4b7508e7324112a53a614fbd61ba6f212b0213f9fa6c8fc351e49bb973a2a519b79f79bcdacb4a726a8c2bac12f2f021576079ab06f047c3673040e1787fc9795864c6957482e0e83dd51eddee32c9c71f63890b37bb31278b1a2dfe441c51c7b769e2c0bbda5a0b285ddccd19dc41cc707544fbe3ccd5ad48ebff3fe5ff9fa3b734625a0f39b52cf545083a25b5ce2a075c00bf5a3dde3fd17ffe3ba0eb2f4b488ab541c49233fa91b56ddd01cd928cf0238e07ece6f0be7beb08e3f8ac6b1a4127d173998b81738fe63292d232a8e2d01869e1292a408a0854b0dbd45477d8212244
2019-04-13 14:43:13,707 - keeper - DEBUG - Loaded Dispenser at 0xcc2353edb989BCcFeb682aeEB7D56497F61fdbfA
2019-04-13 14:43:13,707 - keeper - DEBUG - Loaded OceanToken at 0xE6F83ee0815e8A9A23146677B66D959f776ea07e
2019-04-13 14:43:13,707 - keeper - DEBUG - Loaded DIDRegistry at 0xC6Db052cb5b24054B60EE4d1aFaBdB345452B39e
2019-04-13 14:43:13,707 - keeper - DEBUG - Loaded TemplateStoreManager at 0x94e47a2516249De6c44d0aab42f94b74f93e4854
2019-04-13 14:43:13,707 - keeper - DEBUG - Loaded EscrowAccessSecretStoreTemplate at 0x49917665Dd169FBbb7752A7903F99Dde96E01B7A
2019-04-13 14:43:13,707 - keeper - DEBUG - Loaded AgreementStoreManager at 0xA5481Ff71862A4240152948f63aC927fc116133f
2019-04-13 14:43:13,707 - keeper - DEBUG - Loaded ConditionStoreManager at 0x014A75Ffe45e7A54aE8811Bf4B50A6C0Ef7C43D8
2019-04-13 14:43:13,707 - keeper - DEBUG - Loaded SignCondition at 0xB4eEEbA76D96F11F3C644Bb80B556f4eA622f1D0
2019-04-13 14:43:13,707 - keeper - DEBUG - Loaded LockRewardCondition at 0xBF7D4cfE97b52E79CcBADa7443472789d8E50ac4
2019-04-13 14:43:13,708 - keeper - DEBUG - Loaded EscrowReward at 0x8F730c1fC2618fefAac911486f4965d002491C4b
2019-04-13 14:43:13,708 - keeper - DEBUG - Loaded AccessSecretStoreCondition at 0x8147bf0C5e331D19c541ee3EbA40a72837352A2e
2019-04-13 14:43:13,708 - keeper - DEBUG - Loaded HashLockCondition at 0x736DCC96D89cB2F9E2316cD826668f4E1c4861B0
2019-04-13 14:43:13,708 - ddo - DEBUG - Adding service with service type <squid_py.ddo.service.Service object at 0x7f44258a4d68> with did did:op:1c61e39a0f694b74b66e82f68fcd3b3bdc3aeb063fba49f7ad120e2616017b69
2019-04-13 14:43:13,708 - ddo - DEBUG - Adding service with service type <squid_py.agreements.service_agreement.ServiceAgreement object at 0x7f4421e0af98> with did did:op:1c61e39a0f694b74b66e82f68fcd3b3bdc3aeb063fba49f7ad120e2616017b69
2019-04-13 14:43:13,708 - ddo - DEBUG - Adding service with service type <squid_py.ddo.service.Service object at 0x7f4421e0afd0> with did did:op:1c61e39a0f694b74b66e82f68fcd3b3bdc3aeb063fba49f7ad120e2616017b69
2019-04-13 14:43:13,708 - ocean - DEBUG - Generated ddo and services, DID is did:op:1c61e39a0f694b74b66e82f68fcd3b3bdc3aeb063fba49f7ad120e2616017b69, metadata service @http://localhost:5000/api/v1/aquarius/assets/ddo/did:op:1c61e39a0f694b74b66e82f68fcd3b3bdc3aeb063fba49f7ad120e2616017b69, `Access` service purchase @http://localhost:12001.
2019-04-13 14:43:13,719 - ocean - DEBUG - Asset/ddo published successfully in aquarius.
2019-04-13 14:43:15,275 - ocean - INFO - DDO with DID did:op:1c61e39a0f694b74b66e82f68fcd3b3bdc3aeb063fba49f7ad120e2616017b69 successfully registered on chain.
2019-04-13 14:43:15,297 - keeper - DEBUG - found did did:op:1c61e39a0f694b74b66e82f68fcd3b3bdc3aeb063fba49f7ad120e2616017b69 -> url=http://localhost:5000/api/v1/aquarius/assets/ddo/did:op:1c61e39a0f694b74b66e82f68fcd3b3bdc3aeb063fba49f7ad120e2616017b69
2019-04-13 14:43:15,303 - ocean - INFO - Searching asset containing: Ocean protocol
did:op:5b8d18fc6fe44e7ba760e5c4a779662f33bdda945ebb43719d5818e54e7e88ca
Traceback (most recent call last):
  File "/home/a690251/projects/odyssey/Heimdallr/usage.py", line 45, in <module>
    service_agreement_id = ocean.assets.order(asset_ddo.did, 0, consumer_account)
  File "/home/a690251/projects/odyssey/Heimdallr/squid_py/ocean/ocean_assets.py", line 275, in order
    did, service_definition_id, consumer_account
  File "/home/a690251/projects/odyssey/Heimdallr/squid_py/ocean/ocean_agreements.py", line 58, in prepare
    asset = self._asset_resolver.resolve(did)
  File "/home/a690251/projects/odyssey/Heimdallr/squid_py/did_resolver/did_resolver.py", line 42, in resolve
    url = self.get_resolve_url(did_bytes)
  File "/home/a690251/projects/odyssey/Heimdallr/squid_py/did_resolver/did_resolver.py", line 52, in get_resolve_url
    data = self._did_registry.get_registered_attribute(did_bytes)
  File "/home/a690251/projects/odyssey/Heimdallr/squid_py/keeper/didregistry.py", line 189, in get_registered_attribute
    f'DID "{did}" is not found on-chain in the current did registry. '
squid_py.exceptions.OceanDIDNotFound: DID "0x5b8d18fc6fe44e7ba760e5c4a779662f33bdda945ebb43719d5818e54e7e88ca" is not found on-chain in the current did registry. Please ensure assets are registered in the correct keeper contracts. The keeper-contracts DIDRegistry address is 0xC6Db052cb5b24054B60EE4d1aFaBdB345452B39e

Process finished with exit code 1

**Comment by eruizgar91** [comment]
As we saw during the Hackathon this error was because using a wrong contract.
