### ISSUE TITLE
Ordering a fresh made asset results in an AssertionError

### ISSUE THREAD

**Issue by weetok** [oceanprotocol/squid-py#342]
## Expected Behavior

We order and get the asset.

## Current Behavior
 
Throws AssertionError

## Failure Information (for bugs)

Traceback (most recent call last):
  File "/home/a690251/projects/odyssey/Heimdallr-py/usage.py", line 45, in <module>
    service_agreement_id = ocean.assets.order(ddo.did, 0, consumer_account)
  File "/home/a690251/projects/odyssey/Heimdallr-py/squid_py/ocean/ocean_assets.py", line 275, in order
    did, service_definition_id, consumer_account
  File "/home/a690251/projects/odyssey/Heimdallr-py/squid_py/ocean/ocean_agreements.py", line 59, in prepare
    service_agreement = ServiceAgreement.from_ddo(service_definition_id, asset)
  File "/home/a690251/projects/odyssey/Heimdallr-py/squid_py/agreements/service_agreement.py", line 155, in from_ddo
    return cls.from_service_dict(service_def)
  File "/home/a690251/projects/odyssey/Heimdallr-py/squid_py/agreements/service_agreement.py", line 166, in from_service_dict
    ServiceAgreementTemplate(service_dict),
  File "/home/a690251/projects/odyssey/Heimdallr-py/squid_py/agreements/service_agreement_template.py", line 21, in __init__
    self.parse_template_json(template_json)
  File "/home/a690251/projects/odyssey/Heimdallr-py/squid_py/agreements/service_agreement_template.py", line 41, in parse_template_json
    assert template_json['type'] == self.DOCUMENT_TYPE, ''
AssertionError

## Step to Reproduce the problem

Please provide detailed steps for reproducing the issue.

1. create a new asset (ocean.assets.create()) with producer account
2. get a consumer account
3. order the asset with the consumer account (ocean.assets.order())

## Specifications

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Version: 0.5.14
* Python: 3.7
* OS: linux, archlinux

## Failure Logs
2019-04-13 17:23:38 XXX root[7012] INFO Logging configuration loaded from file: logging.yaml
2019-04-13 17:23:38,318 - keeper - DEBUG - Loaded Dispenser at 0x053dc56D2C6A87FB6CEb1063E4c1629B8Cc67F82
2019-04-13 17:23:38,363 - keeper - DEBUG - Loaded OceanToken at 0xF92A9C860f329ddc4750368e8DbB80D054CD8F0f
2019-04-13 17:23:38,397 - keeper - DEBUG - Loaded DIDRegistry at 0x0C2c0a4d148e9724065ec91875Af52597CCa82E1
2019-04-13 17:23:38,420 - keeper - DEBUG - Loaded TemplateStoreManager at 0x5E2B554B115b0d428747F3f69CBbC808bA68C34A
2019-04-13 17:23:38,451 - keeper - DEBUG - Loaded EscrowAccessSecretStoreTemplate at 0xB4d05b7D929dD241b79e06FF1AeA033159693931
2019-04-13 17:23:38,476 - keeper - DEBUG - Loaded AgreementStoreManager at 0xBDB91cF0a8449a2848Ba6194eE45579E81B1A0F9
2019-04-13 17:23:38,521 - keeper - DEBUG - Loaded ConditionStoreManager at 0x7256EdE4Bd3D79a8Cc03a2A74849506F5C90c614
2019-04-13 17:23:38,552 - keeper - DEBUG - Loaded SignCondition at 0xFc0Ef2d1eA7d06401066af9c7F67b1bc2A688df7
2019-04-13 17:23:38,575 - keeper - DEBUG - Loaded LockRewardCondition at 0x886dE2b3F8F27eEd43bA2FD4bC2AabDc14E0d9dD
2019-04-13 17:23:38,598 - keeper - DEBUG - Loaded EscrowReward at 0xFF3a12191A703939b1466eC1Fc7679AbbFf88545
2019-04-13 17:23:38,621 - keeper - DEBUG - Loaded AccessSecretStoreCondition at 0xF673Cd200CEa6FAB788979BD475cC595d5894767
2019-04-13 17:23:38 XXX squid_py.ocean.ocean_secret_store[7012] INFO 	SecretStore: url http://localhost:12001, parity-client http://localhost:8545, account 0x00Bd138aBD70e2F00903268F3Db08f2D25677C9e
2019-04-13 17:23:38 XXX squid_py.keeper.diagnostics[7012] INFO Keeper contract artifacts (JSON abi files) at: /home/a690251/projects/odyssey/Heimdallr-py/artifacts
2019-04-13 17:23:38,647 - keeper - DEBUG - Loaded HashLockCondition at 0xf70542C3FD62e8050720F648b8c5Bd727d88D81A
2019-04-13 17:23:38 XXX squid_py.keeper.diagnostics[7012] INFO Using keeper contracts from network spree, network id is 8996
2019-04-13 17:23:38 XXX squid_py.keeper.diagnostics[7012] INFO Looking for keeper contracts ending with ".spree.json", e.g. "AgreementStoreManager.spree.json".
2019-04-13 17:23:38,661 - keeper - DEBUG - Loaded Dispenser at 0x053dc56D2C6A87FB6CEb1063E4c1629B8Cc67F82
2019-04-13 17:23:38,662 - keeper - DEBUG - Loaded OceanToken at 0xF92A9C860f329ddc4750368e8DbB80D054CD8F0f
2019-04-13 17:23:38,662 - keeper - DEBUG - Loaded DIDRegistry at 0x0C2c0a4d148e9724065ec91875Af52597CCa82E1
2019-04-13 17:23:38,662 - keeper - DEBUG - Loaded TemplateStoreManager at 0x5E2B554B115b0d428747F3f69CBbC808bA68C34A
2019-04-13 17:23:38,662 - keeper - DEBUG - Loaded EscrowAccessSecretStoreTemplate at 0xB4d05b7D929dD241b79e06FF1AeA033159693931
2019-04-13 17:23:38,662 - keeper - DEBUG - Loaded AgreementStoreManager at 0xBDB91cF0a8449a2848Ba6194eE45579E81B1A0F9
2019-04-13 17:23:38,662 - keeper - DEBUG - Loaded ConditionStoreManager at 0x7256EdE4Bd3D79a8Cc03a2A74849506F5C90c614
2019-04-13 17:23:38,662 - keeper - DEBUG - Loaded SignCondition at 0xFc0Ef2d1eA7d06401066af9c7F67b1bc2A688df7
2019-04-13 17:23:38,662 - keeper - DEBUG - Loaded LockRewardCondition at 0x886dE2b3F8F27eEd43bA2FD4bC2AabDc14E0d9dD
2019-04-13 17:23:38,663 - keeper - DEBUG - Loaded EscrowReward at 0xFF3a12191A703939b1466eC1Fc7679AbbFf88545
2019-04-13 17:23:38,663 - keeper - DEBUG - Loaded AccessSecretStoreCondition at 0xF673Cd200CEa6FAB788979BD475cC595d5894767
2019-04-13 17:23:38,663 - keeper - DEBUG - Loaded HashLockCondition at 0xf70542C3FD62e8050720F648b8c5Bd727d88D81A
2019-04-13 17:23:38,663 - ocean - INFO - Squid Ocean instance initialized: 
2019-04-13 17:23:38,663 - ocean - INFO - 	Other accounts: ['0x00Bd138aBD70e2F00903268F3Db08f2D25677C9e', '0x068Ed00cF0441e4829D9784fCBe7b9e26D4BD8d0', '0xA99D43d86A0758d5632313b8fA3972B6088A21BB']
2019-04-13 17:23:38 XXX root[7012] INFO Finished loading keeper contracts:
	Dispenser: 0x053dc56D2C6A87FB6CEb1063E4c1629B8Cc67F82
	OceanToken: 0xF92A9C860f329ddc4750368e8DbB80D054CD8F0f
	DIDRegistry: 0x0C2c0a4d148e9724065ec91875Af52597CCa82E1
	AgreementStoreManager: 0xBDB91cF0a8449a2848Ba6194eE45579E81B1A0F9
	TemplateStoreManager: 0x5E2B554B115b0d428747F3f69CBbC808bA68C34A
	ConditionStoreManager: 0x7256EdE4Bd3D79a8Cc03a2A74849506F5C90c614
	AccessSecretStoreCondition: 0xF673Cd200CEa6FAB788979BD475cC595d5894767
	SignCondition: 0xFc0Ef2d1eA7d06401066af9c7F67b1bc2A688df7
	LockRewardCondition: 0x886dE2b3F8F27eEd43bA2FD4bC2AabDc14E0d9dD
	EscrowAccessSecretStoreTemplate: 0xB4d05b7D929dD241b79e06FF1AeA033159693931
	EscrowReward: 0xFF3a12191A703939b1466eC1Fc7679AbbFf88545
	HashLockCondition: 0xf70542C3FD62e8050720F648b8c5Bd727d88D81A
2019-04-13 17:23:38,663 - ocean - INFO - 	DIDRegistry @ 0x0C2c0a4d148e9724065ec91875Af52597CCa82E1
2019-04-13 17:23:38,664 - ocean - DEBUG - Generating new did: did:op:1974a4e7e38444f5bdf38f61f1e35c321dbc8ebc22144def8bd6e088657ecbe2
2019-04-13 17:23:38,709 - ddo - DEBUG - Adding public key 0x00Bd138aBD70e2F00903268F3Db08f2D25677C9e to the did did:op:1974a4e7e38444f5bdf38f61f1e35c321dbc8ebc22144def8bd6e088657ecbe2
2019-04-13 17:23:38,709 - ddo - DEBUG - Adding authentication {'type': 'RsaSignatureAuthentication2018', 'publicKey': 'did:op:1974a4e7e38444f5bdf38f61f1e35c321dbc8ebc22144def8bd6e088657ecbe2'}
2019-04-13 17:23:38,871 - ddo - DEBUG - Adding signature to the ddo object.
2019-04-13 17:23:38,871 - ocean - DEBUG - Encrypting content urls in the metadata.
2019-04-13 17:23:38,980 - ocean - INFO - Content urls encrypted successfully 0xf840ba094b95de3385459c204527980db465b9876bd08b9ed13ee851fb4a7e87025b6ff3621a951a896b1e2981294b8d52c2f4ed8884d50a85815a50c083fd98653feefd4d7d9ca27d1cac37faecd1507a91d5c2864259cfc6eaf0f8e09bfd27ab8b00316d537a8591b56c01668af4c4224f24b8c76b9c9b9878edb167022283e428f972600dac37ece2714d1e94d42e79a3de94e21f9fd12303cefb740f73d300d269a0db8475fcadad05998532cea14061c3d54ae7d58ff9a0b736933bbf380fd67f3c72aa6e9d1e4ea0bb185c748878edf84a35e6b42dfc695628bb2650bf8880e9fcf51960ef349d1ae58d7753fd02489ec2b2fd69d25ba069b63326a53712985637b23d5356359090997fc09ac6e2ef761b341a11c68d2c8b63c10be34fb1785cea66fe1ed4b109adcd48d70f932e3432c1f7e735770d8ed7ee06e81efd369397ee77867192b1933e2db8b34664e634be12cc9e603d691249efc06de15d55936f0b0c9d0e9a44895fcd6c492df2b075143ebf843f4c391b134b7481b2dc01ca6f4bfd8a5be73b62cc639bcdd3299b85cc04fc9eb0094e95c7f293a52a2f78cfcebbc2a251d0c2f95e2b8a9a3d5db8cb681e86cbc06c862c1630ab63b5dc078dc1b1b43fd779d90bec90c561b32792aeb9b9be9c743d50e2cffdc972db3799b60b588cbb4944d4efb6b1511c68ee3b18cc2b61f46fc533eb0b6393d233b18d1cbc018f81ededd3c43dc0bdcf64f264fbd2a2171572fcae2d
2019-04-13 17:23:38,989 - keeper - DEBUG - Loaded Dispenser at 0x053dc56D2C6A87FB6CEb1063E4c1629B8Cc67F82
2019-04-13 17:23:38,989 - keeper - DEBUG - Loaded OceanToken at 0xF92A9C860f329ddc4750368e8DbB80D054CD8F0f
2019-04-13 17:23:38,989 - keeper - DEBUG - Loaded DIDRegistry at 0x0C2c0a4d148e9724065ec91875Af52597CCa82E1
2019-04-13 17:23:38,990 - keeper - DEBUG - Loaded TemplateStoreManager at 0x5E2B554B115b0d428747F3f69CBbC808bA68C34A
2019-04-13 17:23:38,990 - keeper - DEBUG - Loaded EscrowAccessSecretStoreTemplate at 0xB4d05b7D929dD241b79e06FF1AeA033159693931
2019-04-13 17:23:38,990 - keeper - DEBUG - Loaded AgreementStoreManager at 0xBDB91cF0a8449a2848Ba6194eE45579E81B1A0F9
2019-04-13 17:23:38,990 - keeper - DEBUG - Loaded ConditionStoreManager at 0x7256EdE4Bd3D79a8Cc03a2A74849506F5C90c614
2019-04-13 17:23:38,990 - keeper - DEBUG - Loaded SignCondition at 0xFc0Ef2d1eA7d06401066af9c7F67b1bc2A688df7
2019-04-13 17:23:38,990 - keeper - DEBUG - Loaded LockRewardCondition at 0x886dE2b3F8F27eEd43bA2FD4bC2AabDc14E0d9dD
2019-04-13 17:23:38,990 - keeper - DEBUG - Loaded EscrowReward at 0xFF3a12191A703939b1466eC1Fc7679AbbFf88545
2019-04-13 17:23:38,990 - keeper - DEBUG - Loaded AccessSecretStoreCondition at 0xF673Cd200CEa6FAB788979BD475cC595d5894767
2019-04-13 17:23:38,991 - keeper - DEBUG - Loaded HashLockCondition at 0xf70542C3FD62e8050720F648b8c5Bd727d88D81A
2019-04-13 17:23:38,992 - ddo - DEBUG - Adding service with service type <squid_py.ddo.service.Service object at 0x7f3a38c79828> with did did:op:1974a4e7e38444f5bdf38f61f1e35c321dbc8ebc22144def8bd6e088657ecbe2
2019-04-13 17:23:38,992 - ddo - DEBUG - Adding service with service type <squid_py.agreements.service_agreement.ServiceAgreement object at 0x7f3a343d5358> with did did:op:1974a4e7e38444f5bdf38f61f1e35c321dbc8ebc22144def8bd6e088657ecbe2
2019-04-13 17:23:38,992 - ddo - DEBUG - Adding service with service type <squid_py.ddo.service.Service object at 0x7f3a343d5dd8> with did did:op:1974a4e7e38444f5bdf38f61f1e35c321dbc8ebc22144def8bd6e088657ecbe2
2019-04-13 17:23:38,993 - ocean - DEBUG - Generated ddo and services, DID is did:op:1974a4e7e38444f5bdf38f61f1e35c321dbc8ebc22144def8bd6e088657ecbe2, metadata service @http://localhost:5000/api/v1/aquarius/assets/ddo/did:op:1974a4e7e38444f5bdf38f61f1e35c321dbc8ebc22144def8bd6e088657ecbe2, `Access` service purchase @http://localhost:12001.
2019-04-13 17:23:39,025 - ocean - DEBUG - Asset/ddo published successfully in aquarius.
2019-04-13 17:23:39,199 - ocean - INFO - DDO with DID did:op:1974a4e7e38444f5bdf38f61f1e35c321dbc8ebc22144def8bd6e088657ecbe2 successfully registered on chain.
2019-04-13 17:23:39,251 - keeper - DEBUG - found did did:op:1974a4e7e38444f5bdf38f61f1e35c321dbc8ebc22144def8bd6e088657ecbe2 -> url=http://localhost:5000/api/v1/aquarius/assets/ddo/did:op:1974a4e7e38444f5bdf38f61f1e35c321dbc8ebc22144def8bd6e088657ecbe2

Traceback (most recent call last):
  File "/home/a690251/projects/odyssey/Heimdallr-py/usage.py", line 45, in <module>
    service_agreement_id = ocean.assets.order(ddo.did, 0, consumer_account)
  File "/home/a690251/projects/odyssey/Heimdallr-py/squid_py/ocean/ocean_assets.py", line 275, in order
    did, service_definition_id, consumer_account
  File "/home/a690251/projects/odyssey/Heimdallr-py/squid_py/ocean/ocean_agreements.py", line 59, in prepare
    service_agreement = ServiceAgreement.from_ddo(service_definition_id, asset)
  File "/home/a690251/projects/odyssey/Heimdallr-py/squid_py/agreements/service_agreement.py", line 155, in from_ddo
    return cls.from_service_dict(service_def)
  File "/home/a690251/projects/odyssey/Heimdallr-py/squid_py/agreements/service_agreement.py", line 166, in from_service_dict
    ServiceAgreementTemplate(service_dict),
  File "/home/a690251/projects/odyssey/Heimdallr-py/squid_py/agreements/service_agreement_template.py", line 21, in __init__
    self.parse_template_json(template_json)
  File "/home/a690251/projects/odyssey/Heimdallr-py/squid_py/agreements/service_agreement_template.py", line 41, in parse_template_json
    assert template_json['type'] == self.DOCUMENT_TYPE, ''
AssertionError

Process finished with exit code 1

**Comment by eruizgar91** [comment]
That is out of date.
