### ISSUE TITLE
Documentation is not up-to-date

### ISSUE THREAD

**Issue by arsenyjin** [oceanprotocol/squid-py#421]
While running the code from the `Usage` section of documentation in `develop` branch(https://github.com/oceanprotocol/squid-py#usage) I ran into several issues, such as:

```
Traceback (most recent call last):
  File "test.py", line 4, in <module>
    from squid_py import (
ImportError: cannot import name 'Metadata'
```
If I comment out `Metadata`, I get the same error with `Account`

**Comment by BenSchZA** [comment]
Is there a simple solution? Otherwise I'll start digging.

**Comment by BenSchZA** [comment]
This seems to work:

```
from ocean_utils.ddo.metadata import Metadata
from ocean_keeper.account import Account

from squid_py import Ocean, ConfigProvider, Config
```

**Comment by BenSchZA** [comment]
The config file format has also changed, and should be in TOML format, as seen here: https://github.com/oceanprotocol/squid-py/blob/develop/config.ini

**Comment by arsenyjin** [comment]
Thanks @BenSchZA ! The new imports format does work for me as well as config, however on `ocean = Ocean()`  I run into following error:

```
Traceback (most recent call last):
  File "test.py", line 12, in <module>
    ocean = Ocean() # or Ocean(Config('config.ini'))
  File "/home/x332/.local/lib/python3.6/site-packages/squid_py/ocean/ocean.py", line 86, in __init__
    self._keeper = Keeper.get_instance(contracts)
  File "/home/x332/.local/lib/python3.6/site-packages/squid_py/ocean/keeper.py", line 12, in get_instance
    return SquidKeeper(contract_names)
  File "/home/x332/.local/lib/python3.6/site-packages/ocean_keeper/keeper.py", line 59, in __init__
    contract = GenericContract(name)
  File "/home/x332/.local/lib/python3.6/site-packages/ocean_keeper/contract_base.py", line 36, in __init__
    self.contract_concise = contract_handler.get_concise_contract(contract_name)
  File "/home/x332/.local/lib/python3.6/site-packages/ocean_keeper/contract_handler.py", line 54, in get_concise_contract
    return (ContractHandler._contracts.get(name) or ContractHandler._load(name))[1]
  File "/home/x332/.local/lib/python3.6/site-packages/ocean_keeper/contract_handler.py", line 96, in _load
    contract_name, ContractHandler.artifacts_path)
  File "/home/x332/.local/lib/python3.6/site-packages/ocean_keeper/contract_handler.py", line 131, in get_contract_dict_by_name
    artifacts_path, contract_name, network_name, artifacts_path)
  File "/home/x332/.local/lib/python3.6/site-packages/ocean_keeper/contract_handler.py", line 110, in _get_contract_file_path
    for name in os.listdir(_base_path):
FileNotFoundError: [Errno 2] No such file or directory: '/usr/artifacts'
```

**Comment by BenSchZA** [comment]
Yep! Slowly figuring out what needs to change, running the script `./scripts/wait_for_migration_and_extract_keeper_artifacts.sh` first should load the Keeper artifacts from the local Barge Docker container.

**Comment by BenSchZA** [comment]
Stuck on the following error from web3 now, after making a number of updates to the example script:

```
Could not identify the intended function with name `isTemplateApproved`, positional argument(s) of type `(<class 'str'>,)` and keyword argument(s) of type `{}`.
Found 1 function(s) with the name `isTemplateApproved`: ['isTemplateApproved(address)']
Function invocation failed due to no matching argument types.
```

**Comment by BenSchZA** [comment]
I've got a feeling the Barge stack Keeper versions etc. are out of sync with the latest updates to this library.

**Comment by BenSchZA** [comment]
WIP example, taking extracts from `examples/` directory to update README version:

```
import os
import time

from examples import example_metadata

from ocean_utils.ddo.metadata import Metadata
from ocean_utils.agreements.service_agreement import ServiceAgreement
from ocean_utils.agreements.service_types import ServiceTypes
from ocean_keeper.account import Account
from ocean_keeper.utils import get_account
from squid_py import Ocean, ConfigProvider, Config

ConfigProvider.set_config(Config('config.ini'))
# Make a new instance of Ocean
ocean = Ocean()  # or Ocean(Config('config.ini'))
config = ocean.config
# make account instance, assuming the ethereum account and password are set
# in the config file `config.ini`
#account = ocean.accounts.list()[0]
# or
#account = Account(config.parity_address, config.parity_password)
account = get_account(0)

# PUBLISHER
# Let's start by registering an asset in the Ocean network
#metadata = Metadata.get_example()
metadata = example_metadata.metadata 

# consume and service endpoints require `brizo.url` is set in the config file
# or passed to Ocean instance in the config_dict.
# define the services to include in the new asset DDO

ddo = ocean.assets.create(metadata, account, providers=[], use_secret_store=True)
assert ddo is not None, f'Registering asset on-chain failed.'

# Now we have an asset registered, we can verify it exists by resolving the did
_ddo = ocean.assets.resolve(ddo.did)
# ddo and _ddo should be identical
print(_ddo.did)

# CONSUMER
# search for assets
asset_ddo = ocean.assets.search("Ocean protocol")[0]
# Need some ocean tokens to be able to order assets
ocean.accounts.request_tokens(account, 10)

# Start the purchase/consume request. This will automatically make a payment from the specified account.
consumer_account = ocean.accounts.list()[0]

service = ddo.get_service(service_type=ServiceTypes.ASSET_ACCESS)
sa = ServiceAgreement.from_json(service.as_dictionary())

agreement_id, signature = ocean.agreements.prepare(
        ddo.did,
        consumer_account,
        sa.index
    )
print(agreement_id)
time.sleep(20)

#sa.index, "Access"
service_agreement_id = ocean.assets.order(ddo.did, sa.index, consumer_account, auto_consume=False)

time.sleep(20)

ocean.assets.consume(agreement_id, ddo.did, sa.index, consumer_account, config.downloads_path)

# after a short wait (seconds to minutes) the asset data files should be available in the `downloads.path` defined in config
# wait a bit to let things happen
time.sleep(20)

# Asset files are saved in a folder named after the asset id
dataset_dir = os.path.join(
    ocean.config.downloads_path, f"datafile.{asset_ddo.asset_id}.0"
)
if os.path.exists(dataset_dir):
    print("asset files downloaded: {}".format(os.listdir(dataset_dir)))
```

**Comment by arsenyjin** [comment]
Cool stuff @BenSchZA , do you want to make a PR?

**Comment by arsenyjin** [comment]
Some additional updates to add to the documentation are:

In development section 
1.  run `TEST_TIER=e2e`
2.  run `source accounts.sh`
3.  change barge options to `./start_ocean.sh --latest --no-commons --no-dashboard --no-agent --no-faucet --local-spree-node`

add `accounts.sh` file with the following content:

```
export PARITY_ADDRESS=0x00bd138abd70e2f00903268f3db08f2d25677c9e
export PARITY_PASSWORD=node0
export PARITY_KEYFILE1=./tests/resources/data/key_file_1.json
export PARITY_ADDRESS1=0x068ed00cf0441e4829d9784fcbe7b9e26d4bd8d0
export PARITY_PASSWORD1=secret
export PARITY_KEYFILE=./tests/resources/data/key_file_2.json
```

**Comment by BenSchZA** [comment]
@arsenyjin I'll add the WIP to a PR this evening and we can continue discussion there :+1:

**Comment by arsenyjin** [comment]
Cool, please PR to `fix/documentation` branch

**Comment by arsenyjin** [comment]
TODO: 
delete flag `--latest` from:

> 3. change barge options to `./start_ocean.sh --latest --no-commons --no-dashboard --no-agent --no-faucet --local-spree-node`
